version: "3.3"

# Production deployment for cutsolver
# Includes simple infrastructure with Caddy (ports 80/443)

services:
  cutsolver_frontend:
    # use specific tags for a persistent reference
    image: modischfabrications/cutsolver_frontend:1.1.2
    restart: unless-stopped
    environment:
      - VUE_APP_BACKEND_SOLVER_URL=https://${DOMAIN_NAME:?err}/
    networks:
      - webserver
    depends_on:
      - cutsolver

  cutsolver:
    image: modischfabrications/cutsolver:1.1.0
    restart: unless-stopped
    environment:
      # can be increased to 1k or something once >=v1.0.3
      - BRUTEFORCE_MAX_COMBINATIONS=8000
      - SOLVER_N_MAX=1500
    networks:
      - webserver

  caddy:
    image: caddy:2.11-alpine
    restart: unless-stopped
    environment:
      - EMAIL_ADDRESS=${EMAIL_ADDRESS:?err}
      - DOMAIN_NAME=${DOMAIN_NAME:?err}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - 80:80
      - 443:443
    networks:
      - webserver

networks:
  webserver:
    name: webserver
    driver: bridge
